/**
 * cities.js — birth-city lookup over src/data/cities.json.
 *
 * City data © GeoNames (https://www.geonames.org/), CC BY 4.0 — credit
 * "GeoNames" in the UI. The JSON is generated by tools/build-cities.mjs:
 *   { v: 1, tz: [iana], cc: {ISO2: 中文国名}, a1: [地区名],
 *     c: [[zh, en, a1Idx, cc, lat, lon, tzIdx, pop], ...] }   // pop desc
 *
 * Usage:
 *   await loadCities(new URL('../data/cities.json', import.meta.url));
 *   searchCities('杭州')  // -> [{ id, name, en, region, country, cc, lat, lon, tz, label }]
 *
 * All lookups other than loadCities() are synchronous and return empty
 * results / null until the data has loaded (see citiesReady()).
 */

const Z = 0; // zh
const EN = 1;
const A1 = 2;
const CC = 3;
const LAT = 4;
const LON = 5;
const TZ = 6;

let loading = null; // memoized promise
let data = null; // parsed JSON
let zhKeys = null; // normalized zh name per row ('' if none)
let enKeys = null; // normalized English name per row
let a1Keys = null; // normalized region names
let tzCanon = null; // lazily built: browser-canonical tz id -> tz index

const HAN = /\p{Script=Han}/u;
const SPECIAL = { ø: 'o', æ: 'ae', œ: 'oe', ß: 'ss', ł: 'l', đ: 'd', ð: 'd', þ: 'th', ı: 'i' };
const COUNTRY_ALIASES = { uk: 'GB', usa: 'US', america: 'US' };

/** lowercase, strip diacritics, drop spaces/punctuation (keeps letters, digits, Han). */
function norm(s) {
  return String(s ?? '')
    .trim()
    .toLowerCase()
    .normalize('NFD')
    .replace(/\p{M}+/gu, '')
    .replace(/[øæœßłđðþı]/g, (ch) => SPECIAL[ch])
    .replace(/[^\p{L}\p{N}]+/gu, '');
}

/**
 * Fetches and indexes the city list once. Subsequent calls return the same
 * promise; a failed load can be retried. Resolves to the number of cities.
 * @param {string|URL} [url] location of cities.json (pass it explicitly when bundling)
 */
export function loadCities(url = 'data/cities.json') {
  if (!loading) {
    loading = fetch(url)
      .then((res) => {
        if (!res.ok) throw new Error(`cities.json: HTTP ${res.status}`);
        return res.json();
      })
      .then((json) => {
        if (!json || json.v !== 1 || !Array.isArray(json.c)) throw new Error('cities.json: unexpected format');
        const n = json.c.length;
        const zk = new Array(n);
        const ek = new Array(n);
        for (let i = 0; i < n; i++) {
          const row = json.c[i];
          zk[i] = row[Z] ? norm(row[Z]) : '';
          ek[i] = norm(row[EN]);
        }
        a1Keys = json.a1.map(norm);
        zhKeys = zk;
        enKeys = ek;
        tzCanon = null;
        data = json;
        return n;
      })
      .catch((err) => {
        loading = null;
        throw err;
      });
  }
  return loading;
}

export function citiesReady() {
  return data !== null;
}

function toResult(id) {
  const row = data?.c[id];
  if (!row) return null;
  const zh = row[Z];
  const name = zh || row[EN];
  const region = row[A1] >= 0 ? data.a1[row[A1]] : '';
  const cc = row[CC];
  const country = data.cc[cc] || cc;

  // label: 杭州 · 浙江 / 多伦多 · 安大略 · 加拿大 / 香港 / 台中 · 中国台湾
  const parts = [name];
  const regionUsable = region && region !== name && !(HAN.test(name) && !HAN.test(region)); // no "吉隆坡 · Kuala Lumpur"
  const countryShown = cc !== 'CN' && country && country !== name && !country.endsWith(name);
  if (regionUsable && !(countryShown && country.endsWith(region))) parts.push(region);
  if (countryShown) parts.push(country);

  return {
    id,
    name,
    en: row[EN],
    region,
    country,
    cc,
    lat: row[LAT],
    lon: row[LON],
    tz: data.tz[row[TZ]],
    label: parts.join(' · '),
  };
}

/** 0 exact, 1 prefix, 2 substring, 3 no match */
function tierOf(key, q) {
  if (!key) return 3;
  if (key === q) return 0;
  const at = key.indexOf(q);
  return at === 0 ? 1 : at > 0 ? 2 : 3;
}

const SAINT = { saint: 'st', st: 'saint', sainte: 'ste', ste: 'sainte' };

/** Normalized query plus equivalent spellings: "st andrews" also tries "saintandrews". */
function queryForms(raw) {
  const forms = [norm(raw)];
  const m = /^(saint|sainte|st|ste)(?:\.\s*|[\s-]+)/i.exec(raw);
  if (m) forms.push(SAINT[m[1].toLowerCase()] + norm(raw.slice(m[0].length)));
  return forms;
}

/** Row ids matching any of the normalized query forms, best tier first, then population. */
function match(forms, filter) {
  const q = forms[0];
  const han = HAN.test(q);
  // query variants with a tier penalty: 杭州市 = 杭州; 宝安区 ≈ 宝安
  const variants = forms.map((f) => [f, 0]);
  if (han && q.length >= 3) {
    if (q.endsWith('市')) variants.push([q.slice(0, -1), 0]);
    else if (/[区县镇乡旗]$/.test(q)) variants.push([q.slice(0, -1), 1]);
  }
  const buckets = [[], [], [], []];
  const rows = data.c;
  for (let i = 0; i < rows.length; i++) {
    let best = 3;
    for (const [v, penalty] of variants) {
      let t = tierOf(zhKeys[i], v);
      if (!han) t = Math.min(t, tierOf(enKeys[i], v));
      if (t < 3) best = Math.min(best, t + penalty);
    }
    if (best < 3 && (!filter || filter(rows[i]))) buckets[best].push(i);
  }
  return buckets[0].concat(buckets[1], buckets[2]);
}

function regionFilter(token) {
  const t = norm(token);
  if (!t) return null;
  const alias = COUNTRY_ALIASES[t] || (t.length === 2 && !HAN.test(t) ? t.toUpperCase() : null);
  return (row) => {
    if (alias && row[CC] === alias) return true;
    if (row[A1] >= 0 && a1Keys[row[A1]].startsWith(t)) return true;
    const country = norm(data.cc[row[CC]]);
    return country.startsWith(t) || (country.length > t.length && country.endsWith(t)); // 台湾 -> 中国台湾
  };
}

/**
 * Search by Chinese name (杭州, 杭州市, 多伦多), English / pinyin (hangzhou,
 * Toronto, "sao paulo") or "城市 地区" (朝阳 辽宁, london ca).
 * Ranking: exact > prefix > substring, then population.
 */
export function searchCities(query, limit = 8) {
  if (!data) return [];
  const raw = String(query ?? '').trim();
  const q = norm(raw);
  if (!q) return [];

  let ids = match(queryForms(raw));

  // loose "city region" form: 朝阳 辽宁 / 辽宁 朝阳 / london ontario
  const tokens = raw.split(/[\s,，、/]+/).filter(Boolean);
  if (tokens.length >= 2) {
    const tries = [
      [tokens.slice(0, -1).join(''), tokens[tokens.length - 1]],
      [tokens.slice(1).join(''), tokens[0]],
    ];
    const seen = new Set();
    const extra = [];
    for (const [city, region] of tries) {
      const forms = queryForms(city);
      const filter = regionFilter(region);
      if (!forms[0] || !filter) continue;
      for (const id of match(forms, filter)) if (!seen.has(id)) { seen.add(id); extra.push(id); }
    }
    // region-qualified hits go first unless the whole string already names a
    // city by exact/prefix match ("new york", "san jose")
    const strong = ids.length > 0 && (zhKeys[ids[0]].startsWith(q) || enKeys[ids[0]].startsWith(q));
    ids = strong ? ids.concat(extra) : extra.concat(ids);
    // nothing matched the qualifier (朝阳 北京): fall back to the city part alone
    if (!ids.length) ids = match(queryForms(tokens.slice(0, -1).join(' ')));
  }

  const out = [];
  const used = new Set();
  for (const id of ids) {
    if (used.has(id)) continue;
    used.add(id);
    out.push(toResult(id));
    if (out.length >= limit) break;
  }
  return out;
}

/** Result object for a city id (index in the data array), or null. */
export function getCity(id) {
  if (!data || !Number.isInteger(id)) return null;
  return toResult(id);
}

const RAD = Math.PI / 180;
function distanceKm(lat1, lon1, lat2, lon2) {
  const dLat = (lat2 - lat1) * RAD;
  const dLon = (lon2 - lon1) * RAD;
  const a = Math.sin(dLat / 2) ** 2 + Math.cos(lat1 * RAD) * Math.cos(lat2 * RAD) * Math.sin(dLon / 2) ** 2;
  return 12742 * Math.asin(Math.min(1, Math.sqrt(a)));
}

/**
 * Nearest city to a point (great-circle distance). If several cities lie
 * within ~15 km of the point, the most populous of them wins, so a location
 * inside a metro area resolves to the metro rather than a suburb.
 */
export function nearestCity(lat, lon) {
  if (!data || !Number.isFinite(lat) || !Number.isFinite(lon)) return null;
  const rows = data.c;
  let nearest = -1;
  let nearestD = Infinity;
  let bigNear = -1; // rows are sorted by population, so the first hit is the biggest
  for (let i = 0; i < rows.length; i++) {
    const d = distanceKm(lat, lon, rows[i][LAT], rows[i][LON]);
    if (d < nearestD) { nearestD = d; nearest = i; }
    if (bigNear < 0 && d <= 15) bigNear = i;
  }
  return toResult(bigNear >= 0 ? bigNear : nearest);
}

function canonicalTz(tz) {
  try {
    return new Intl.DateTimeFormat('en-US', { timeZone: tz }).resolvedOptions().timeZone;
  } catch {
    return null;
  }
}

/**
 * Most populous city in the browser's time zone (a sensible default for the
 * birth-city field), else 北京. Returns null if the cities are not loaded yet.
 */
export function guessHomeCity() {
  if (!data) return null;
  let tzIdx = -1;
  try {
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
    tzIdx = data.tz.indexOf(tz);
    if (tzIdx < 0 && tz) {
      // browsers may report aliases (Asia/Calcutta vs Asia/Kolkata): compare canonical ids
      if (!tzCanon) {
        tzCanon = new Map();
        data.tz.forEach((t, i) => {
          const c = canonicalTz(t);
          if (c && !tzCanon.has(c)) tzCanon.set(c, i);
        });
      }
      tzIdx = tzCanon.get(canonicalTz(tz) ?? tz) ?? -1;
    }
  } catch {
    tzIdx = -1;
  }
  const rows = data.c;
  if (tzIdx >= 0) {
    for (let i = 0; i < rows.length; i++) if (rows[i][TZ] === tzIdx) return toResult(i);
  }
  const beijing = rows.findIndex((r) => r[CC] === 'CN' && r[EN] === 'Beijing');
  return toResult(beijing >= 0 ? beijing : 0);
}
