// content/poems.json (the curated 200-poem library) → src/js/poem-library.js, adding the sky / season /
// pair conditions a poem needs to be TRUE for a given birth night (see poems.js → fits()).
//   node tools/build-poems.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const poems = JSON.parse(fs.readFileSync(path.join(root, 'content/poems.json'), 'utf8'));
const SEASONS = ['春', '夏', '秋', '冬'];

const out = poems.map((p) => {
  const t = new Set(p.themes);
  const when = {};
  if (t.has('有月')) when.moon = 'up';
  if (t.has('无月')) when.moon = 'down';
  if (t.has('蛾眉月')) when.moon = p.kind === 'site' ? 'crescent-up' : 'crescent';
  if (t.has('北半球') || t.has('北极星')) when.north = true;
  const seasons = SEASONS.filter((s) => t.has(s));
  if (seasons.length) when[p.kind === 'site' && !p.pair ? 'seasons' : 'seasonsSoft'] = seasons;
  if (p.pair) {
    if (t.has('年龄差')) when.pairYears = 'diff';
    if (t.has('异地')) when.pairFarKm = 100;
    if (t.has('时差')) when.pairLonDiff = 90;
    if (t.has('冬夏')) when.pairSeasons = ['冬', '夏']; // one born in winter, the other in summer
  }
  return {
    id: p.id, lines: p.lines, by: p.by, title: p.title, kind: p.kind, translator: p.translator,
    themes: p.themes, regions: p.regions, pair: !!p.pair, ...(Object.keys(when).length ? { when } : {}),
  };
});

const header = `// GENERATED by tools/build-poems.mjs from content/poems.json — do not edit by hand.
// ${out.length} poems: { id, lines (1–4), by, title, kind: classic|idiom|site, translator,
//   themes, regions (birthplaces), pair, when? (conditions: moon, north, seasons, seasonsSoft, pair*) }
// kind 'classic': real lines of classical Chinese poetry and prose, quoted with author and title;
// kind 'idiom': a 成语; kind 'site': our own lines written in classical form (no attribution).
`;
fs.writeFileSync(path.join(root, 'src/js/poem-library.js'),
  `${header}export const LIBRARY = [\n${out.map((p) => `  ${JSON.stringify(p)},`).join('\n')}\n];\n`);
const c = (k) => out.filter((p) => p.kind === k).length;
console.log(`poem-library.js: ${out.length} poems (classic ${c('classic')}, idiom ${c('idiom')}, site ${c('site')}), pair ${out.filter((p) => p.pair).length}, conditional ${out.filter((p) => p.when).length}`);
